name: Run Python App

# on:
#   push:
#     branches:
#       - main  # Adjust the branch name if needed
#   pull_request:

on:
  push:
    paths:
      - 'src/**'  # Triggers the workflow only when files in src/ change
    branches:
      - main      
  pull_request:
    paths:
      - 'src/**'
    


jobs:
  run_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12.3'  # Change to your required Python version

      # - name: Install dependencies
      #   run: |
      #     ls -l
      #     pip install -r ./src/Requirement.txt

      # - name: Set up Docker
      #   uses: docker/setup-docker-action@v4          
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          push: true
          tags: praveensingh901/pythonapp:v1